
version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: youtan_django/backend-dockerfile
    container_name: docker-django-backend
    command: ./youtan_django/backend-setup.sh
    volumes:
      - .:/app
    ports:
      - "3002:3000"

  vue:
    build:
      context: .
      dockerfile: youtan_vue/frontend-dockerfile
    container_name: docker-vue-frontend
    command: ./youtan_vue/frontend-setup.sh
    volumes:
      - .:/app
    ports:
      - "8082:8080"
    depends_on:
      - django
