
version: '3.9'

services:
  db:
    restart: always
    image: postgres
    container_name: docker-postgres-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]

  pgadmin:
      # Probabily you are going to use it, but i like to have and pgadmin when using postgres
      image: dpage/pgadmin4
      container_name: docker-pgadmin
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: root
      restart: always
      
  django:
    image: django:dev
    container_name: docker-django-backend
    build: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py devdb
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy

  vue:
    image: vue:dev
    container_name: docker-vue-frontend
    build:
      context: .
      dockerfile: youtan_vue/frontend-dockerfile
    command: >
      bash -c "cd youtan_vue/
      && npm install
      && npm install bulma-toast
      && npm run serve"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - django

volumes:
  postgres_data:
