# Generated by Django 4.1.5 on 2023-02-14 01:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadeFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('cnpj', models.CharField(blank=True, default='', max_length=14)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/veiculos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/veiculos/')),
                ('tipo_veiculo', models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro'), ('van', 'Van')], max_length=5)),
                ('placa', models.CharField(blank=True, default='', max_length=7)),
                ('ano', models.CharField(blank=True, default='', max_length=256)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField()),
                ('minimum_increment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('ended', models.BooleanField(default=False)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entidade_financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidadefinanceira')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leilao')),
            ],
            options={
                'ordering': ('-money_value',),
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/imoveis/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/imoveis/')),
                ('tipo_imovel', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('rural', 'Rural')], max_length=256)),
                ('logradouro', models.CharField(blank=True, default='', max_length=256)),
                ('bairro', models.CharField(blank=True, default='', max_length=256)),
                ('numero', models.CharField(blank=True, default='', max_length=256)),
                ('cep', models.CharField(blank=True, default='', max_length=256)),
                ('cidade', models.CharField(blank=True, default='', max_length=256)),
                ('estado', models.CharField(choices=[('AC', 'Ac'), ('AL', 'Al'), ('AP', 'Ap'), ('AM', 'Am'), ('BA', 'Ba'), ('CE', 'Ce'), ('DF', 'Df'), ('ES', 'Es'), ('GO', 'Go'), ('MA', 'Ma'), ('MT', 'Mt'), ('MS', 'Ms'), ('MG', 'Mg'), ('PA', 'Pa'), ('PB', 'Pb'), ('PR', 'Pr'), ('PE', 'Pe'), ('PI', 'Pi'), ('RJ', 'Rj'), ('RN', 'Rn'), ('RS', 'Rs'), ('RO', 'Ro'), ('RR', 'Rr'), ('SC', 'Sc'), ('SP', 'Sp'), ('SE', 'Se'), ('TO', 'To')], max_length=2)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
