# Generated by Django 4.1.5 on 2023-01-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lance',
            name='created_by',
        ),
    ]
