# Generated by Django 4.1.5 on 2023-01-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidadefinanceira',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='lance',
            options={'ordering': ('-money_value',)},
        ),
        migrations.AlterModelOptions(
            name='leilao',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='entidadefinanceira',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='imovel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/imoveis/'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='imovel',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='imovel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/imoveis/'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/veiculos/'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/veiculos/'),
        ),
    ]
