# Generated by Django 4.1.5 on 2023-01-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entidadefinanceira_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidadefinanceira',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='entidadefinanceira',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='entidadefinanceira',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='entidadefinanceira',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='entidadefinanceira',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='entidadefinanceira',
            name='numero',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='estado',
            field=models.CharField(choices=[('AC', 'Ac'), ('AL', 'Al'), ('AP', 'Ap'), ('AM', 'Am'), ('BA', 'Ba'), ('CE', 'Ce'), ('DF', 'Df'), ('ES', 'Es'), ('GO', 'Go'), ('MA', 'Ma'), ('MT', 'Mt'), ('MS', 'Ms'), ('MG', 'Mg'), ('PA', 'Pa'), ('PB', 'Pb'), ('PR', 'Pr'), ('PE', 'Pe'), ('PI', 'Pi'), ('RJ', 'Rj'), ('RN', 'Rn'), ('RS', 'Rs'), ('RO', 'Ro'), ('RR', 'Rr'), ('SC', 'Sc'), ('SP', 'Sp'), ('SE', 'Se'), ('TO', 'To')], max_length=2),
        ),
    ]
