# Generated by Django 4.1.5 on 2023-01-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lance_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
